name: App
on:
  push:
    paths: ["app/backend/**"]
  workflow_dispatch:
jobs:
  build_scan_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker build -t sf-backend:ci app/backend
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'sf-backend:ci'
          format: 'table'
          exit-code: '0'
      - name: Push to ECR (script)
        run: |
          chmod +x app/backend/push_ecr.sh
          ./app/backend/push_ecr.sh dev
